#!/bin/bash

# DeepSeek Agent Examples
# This script demonstrates the agentic terminal

echo "═══════════════════════════════════════════════════════════"
echo "  DeepSeek Agent - Agentic Terminal Examples"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "This shows what you can do with the agentic terminal"
echo ""
echo "Basic usage: deepseek-agent"
echo "Then just describe what you want to do!"
echo ""
echo "Examples of things you can say:"
echo ""
echo "1. LIST FILES"
echo "   'List files in current directory'"
echo "   'Show me all Python files'"
echo "   'What files are in /Users/juliusalba?'"
echo ""
echo "2. CREATE THINGS"
echo "   'Create a new Python script'"
echo "   'Create a directory called test'"
echo "   'Make a file called README.md'"
echo ""
echo "3. RUN COMMANDS"
echo "   'Install the requests package'"
echo "   'Show disk usage'"
echo "   'Check Python version'"
echo ""
echo "4. SEARCH & FIND"
echo "   'Find all .txt files'"
echo "   'Search for TODO in my code'"
echo "   'Find files larger than 1MB'"
echo ""
echo "5. COMBINED TASKS"
echo "   'Create a virtual environment and install Django'"
echo "   'List all files, then show me the largest one'"
echo "   'Create a project structure with src/ and tests/'"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "To start: deepseek-agent"
echo ""
echo "Or try direct commands:"
echo "  deepseek-agent exec 'ls -la'"
echo "  deepseek-agent read /Users/juliusalba/deepseek-cli.py"
echo "  deepseek-agent ls /Users/juliusalba"
echo ""
echo "═══════════════════════════════════════════════════════════"
